---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: secrets-configmaps-get-put
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "update", "create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "update", "create"]
