---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hadoop-master-role-binding
subjects:
- kind: ServiceAccount
  name: hadoop-master
  namespace: hadoop
roleRef:
  kind: ClusterRole
  name: secrets-configmaps-get-put
  apiGroup: rbac.authorization.k8s.io