---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdfs-nn-pvc
  namespace: hadoop
  labels:
    name: hadoop-master
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
