apiVersion: v1
kind: Service
metadata:
  name: master-service
  namespace: hadoop
spec:
  type: NodePort
  selector:
    name: hadoop-master
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 19888
      targetPort: 19888
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007