apiVersion: v1
kind: PersistentVolume
metadata:
  name: hdfs-namenode-data
  namespace: hadoop
  labels:
    name: hadoop-master
spec:
  storageClassName: manual
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/hdfs"
