apiVersion: v1
kind: PersistentVolume
metadata:
  name: hdfs-data
  namespace: hadoop
  labels:
    name: hadoop-worker
spec:
  storageClassName: manual
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/hdfs"
